name: 'Damn Externalities!'
favicon: null
layout_spectrum: 0.5876972363330424
typography_spectrum: 0.36201327247545123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.012889870442450047
  lightness: 0.2974787352140993
  saturation: 0.38931780913844705
  rhythmicContrast: 0.3906219203490764
purpose: []
